package Vista;

import java.awt.Color;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author J.Vidaurre Al.
 */

public class BuscarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form EditarPacienteNuevo
     */
    
    public BuscarPaciente() {
        initComponents();
        this.setSize(325, 200); //Ajusta tamaño
        this.setLocationRelativeTo(null); //Centra en pantalla
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldDNI = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Paciente");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Ingrese DNI del paciente que desea buscar:");

        textFieldDNI.setBackground(new java.awt.Color(51, 51, 51));
        textFieldDNI.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        textFieldDNI.setForeground(new java.awt.Color(102, 102, 102));
        textFieldDNI.setText("Ingrese DNI...");
        textFieldDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldDNIMouseClicked(evt);
            }
        });

        botonBuscar.setBackground(new java.awt.Color(0, 102, 255));
        botonBuscar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botonBuscar.setText("Buscar Paciente");
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBuscar)
                        .addGap(36, 36, 36)
                        .addComponent(botonCancelar))
                    .addComponent(textFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonCancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getDniIngresado() {
        return textFieldDNI.getText().trim();
    }
    
    public JButton getBotonBuscarPaciente() {
        return botonBuscar;
    }
    
    private void textFieldDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldDNIMouseClicked
        // TODO add your handling code here:
        textFieldDNI.setText("");
        textFieldDNI.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_textFieldDNIMouseClicked

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        // "Window ventana" obtiene la ventana que contiene el botón y la cierra.
        Window ventana = SwingUtilities.getWindowAncestor((JButton) evt.getSource());
        if (ventana != null) {
            ventana.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        //Creamos una instancia de la clase "EditarDatosForm"
        /* EditarDatosForm editarDatosForm = new EditarDatosForm();
        //Configuramos el Frame para que se muestre
        editarDatosForm.setVisible(true);
        // "Window ventana" obtiene la ventana que contiene el botón y la cierra.
        Window ventana = SwingUtilities.getWindowAncestor((JButton) evt.getSource());
        if (ventana != null) {
            ventana.dispose();
        } */
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        //Creamos una instancia de la clase "Paciente Encontrado"
        //PacienteEncontrado mostrarPaciente = new PacienteEncontrado();
        //Configuramos el Frame para que se muestre
        //mostrarPaciente.setLocationRelativeTo(null);  //centra en pantalla
        //mostrarPaciente.toFront();  //trae al frente
        //mostrarPaciente.requestFocus();  //pide el foco
        //mostrarPaciente.setVisible(true);
        // "Window ventana" obtiene la ventana que contiene al botón y la cierra.
        //Window ventana = SwingUtilities.getWindowAncestor((JButton) evt.getSource());
        //if (ventana != null) {
            //ventana.dispose();
        //}
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textFieldDNI;
    // End of variables declaration//GEN-END:variables
}
