package Vista;

import java.awt.Color;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author J. Vidaurre Al.
 */
public class EliminarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public EliminarPaciente() {
        initComponents();
        this.setSize(325, 200); //Ajusta tamaño
        this.setLocationRelativeTo(null); //Centra en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldDNI = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eliminar Paciente");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Ingrese DNI del paciente que desea eliminar:");

        textFieldDNI.setBackground(new java.awt.Color(51, 51, 51));
        textFieldDNI.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        textFieldDNI.setForeground(new java.awt.Color(102, 102, 102));
        textFieldDNI.setText("Ingrese DNI...");
        textFieldDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldDNIMouseClicked(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(102, 0, 0));
        botonEliminar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar Paciente");
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldDNI))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldDNIMouseClicked
        // TODO add your handling code here:
        textFieldDNI.setText("");
        textFieldDNI.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_textFieldDNIMouseClicked

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        // "Window ventana" obtiene la ventana que contiene el botón y la cierra.
        Window ventana = SwingUtilities.getWindowAncestor((JButton) evt.getSource());
        if (ventana != null) {
            ventana.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:      
        // "Window ventana" obtiene la ventana que contiene el botón y la cierra.
        Window ventana = SwingUtilities.getWindowAncestor((JButton) evt.getSource());
        if (ventana != null) {
            ventana.dispose();
        }
        JOptionPane.showMessageDialog(null, "Operación exitosa! ");
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textFieldDNI;
    // End of variables declaration//GEN-END:variables
}
