package Vista;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author J. Vidaurre Al.
 */

public class VentanaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(600, 375); //Ajusta tamaño
        this.setLocationRelativeTo(null); //Centra en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabezado = new javax.swing.JLabel();
        PanelFondo = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Posta Medica");

        Encabezado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Encabezado.setText("Gestión de Pacientes");
        Encabezado.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        getContentPane().add(Encabezado, java.awt.BorderLayout.PAGE_START);

        PanelFondo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        PanelFondo.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        botonAgregar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        botonAgregar.setText("➕ Agregar Paciente");
        botonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        PanelFondo.add(botonAgregar);

        botonEditar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        botonEditar.setText("✏️ Editar Paciente");
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        PanelFondo.add(botonEditar);

        botonEliminar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        botonEliminar.setText("🗑️ Eliminar Paciente");
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        PanelFondo.add(botonEliminar);

        botonBuscar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        botonBuscar.setText("🔍 Buscar Paciente");
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        PanelFondo.add(botonBuscar);

        botonMostrar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        botonMostrar.setText("📋 Mostrar Todos");
        botonMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        PanelFondo.add(botonMostrar);

        botonSalir.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        botonSalir.setText("🚪 Salir");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        PanelFondo.add(botonSalir);

        getContentPane().add(PanelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotonAgregar() {
        return botonAgregar;
    }
    
    public JButton getBotonEliminar() {
        return botonEliminar;
    }
    
    public JButton getBotonMostrar() {
        return botonMostrar;
    }
    
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        //Creamos una instancia de la clase "RegistroNuevoPaciente"
        //RegistroPaciente registro = new RegistroPaciente();
        //Configuramos el frame para que se muestre
        //registro.setVisible(true);
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        //Creamos una instancia de la clase "EliminarPaciente"
        //EliminarPaciente eliminarPaciente = new EliminarPaciente();
        //Configuramos el frame para que se muestre
        //eliminarPaciente.setVisible(true);
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        //Creamos una instancia de la clase "EditarPacienteNuevo"
        EditarDatos1 editarPacienteNuevo = new EditarDatos1();
        //Configuramos el Frame para que se muestre
        editarPacienteNuevo.setVisible(true);
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Disponible próximamente!! ");
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        //Creamos una instancia de la clase "BuscarPaciente"
        BuscarPaciente buscarPaciente = new BuscarPaciente();
        //Configuramos el Frame para que se muestre
        buscarPaciente.setVisible(true);
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encabezado;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonSalir;
    // End of variables declaration//GEN-END:variables
}
